# Generated by Django 4.2.11 on 2025-06-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenny_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MfgPrice',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('region', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=70)),
                ('postal_address', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField()),
            ],
        ),
    ]
